package com.example.firstDraft.service;

import com.example.firstDraft.entity.Alert;
import com.example.firstDraft.entity.AlertHistory;
import com.example.firstDraft.entity.MonitoringRule;
import com.example.firstDraft.entity.RuleExecutionHistory;
import com.example.firstDraft.entity.TransactionRecord;
import com.example.firstDraft.model.RuleExecutionOutcome;
import com.example.firstDraft.model.AlertStatus;
import com.example.firstDraft.model.RuleType;
import com.example.firstDraft.repository.AlertHistoryRepository;
import com.example.firstDraft.repository.AlertRepository;
import com.example.firstDraft.repository.MonitoringRuleRepository;
import com.example.firstDraft.repository.RuleExecutionHistoryRepository;
import com.example.firstDraft.service.ruleengine.RuleEvaluationResult;
import com.example.firstDraft.service.ruleengine.RuleEvaluator;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

@Service
public class RuleEngineService {

    private final MonitoringRuleRepository ruleRepository;
    private final AlertRepository alertRepository;
    private final AlertHistoryRepository historyRepository;
    private final RuleExecutionHistoryRepository ruleExecutionHistoryRepository;
    private final Map<RuleType, RuleEvaluator> evaluatorsByType;

    public RuleEngineService(
        MonitoringRuleRepository ruleRepository,
        AlertRepository alertRepository,
        AlertHistoryRepository historyRepository,
        RuleExecutionHistoryRepository ruleExecutionHistoryRepository,
        List<RuleEvaluator> evaluators
    ) {
        this.ruleRepository = ruleRepository;
        this.alertRepository = alertRepository;
        this.historyRepository = historyRepository;
        this.ruleExecutionHistoryRepository = ruleExecutionHistoryRepository;
        this.evaluatorsByType = buildEvaluatorMap(evaluators);
    }

    public boolean evaluate(TransactionRecord transaction) {
        List<MonitoringRule> activeRules = ruleRepository.findByActiveTrue();
        boolean violated = false;
        String executionId = UUID.randomUUID().toString();

        for (MonitoringRule rule : activeRules) {
            RuleEvaluator evaluator = evaluatorsByType.get(rule.getType());
            if (evaluator == null) {
                saveExecutionHistory(
                    executionId,
                    rule,
                    transaction,
                    RuleExecutionOutcome.NOT_TRIGGERED,
                    "No evaluator registered for rule type " + rule.getType()
                );
                continue;
            }

            Optional<RuleEvaluationResult> result = evaluator.evaluate(transaction, rule);
            if (result.isPresent()) {
                createAlert(rule, result.get());
                saveExecutionHistory(
                    executionId,
                    rule,
                    transaction,
                    RuleExecutionOutcome.TRIGGERED,
                    result.get().reason()
                );
                violated = true;
            } else {
                saveExecutionHistory(
                    executionId,
                    rule,
                    transaction,
                    RuleExecutionOutcome.NOT_TRIGGERED,
                    "Rule conditions not met for transaction"
                );
            }
        }

        return violated;
    }

    private void createAlert(MonitoringRule rule, RuleEvaluationResult result) {
        Instant now = Instant.now();
        Alert alert = new Alert();
        alert.setRuleName(rule.getName());
        alert.setRuleType(rule.getType());
        alert.setSeverity(rule.getSeverity());
        alert.setStatus(AlertStatus.OPEN);
        alert.setMessage(result.reason());
        alert.setCreatedAt(now);
        alert.setUpdatedAt(now);
        alert.setTriggeringTransactions(new ArrayList<>(result.triggeringTransactions()));
        Alert saved = alertRepository.save(alert);

        AlertHistory createdEvent = new AlertHistory();
        createdEvent.setAlert(saved);
        createdEvent.setFromStatus(null);
        createdEvent.setToStatus(AlertStatus.OPEN);
        createdEvent.setNote("Alert generated by rule " + rule.getName() + " (" + rule.getType() + "): " + result.reason());
        createdEvent.setCreatedAt(now);
        historyRepository.save(createdEvent);
    }

    private Map<RuleType, RuleEvaluator> buildEvaluatorMap(List<RuleEvaluator> evaluators) {
        Map<RuleType, RuleEvaluator> map = new EnumMap<>(RuleType.class);
        for (RuleEvaluator evaluator : evaluators) {
            map.put(evaluator.supportedType(), evaluator);
        }
        return map;
    }

    private void saveExecutionHistory(
        String executionId,
        MonitoringRule rule,
        TransactionRecord transaction,
        RuleExecutionOutcome outcome,
        String message
    ) {
        RuleExecutionHistory history = new RuleExecutionHistory();
        history.setExecutionId(executionId);
        history.setRuleId(rule.getId());
        history.setTransactionId(transaction.getId());
        history.setOutcome(outcome);
        history.setMessage(message);
        history.setCreatedAt(Instant.now());
        ruleExecutionHistoryRepository.save(history);
    }
}

